### ISSUE TITLE
Do you have an example of a formatted packages.csv

### ISSUE THREAD

**Issue by sventers** [anvaka/allpypi#1]
Merry Christmas,

I've been trying to build a pm viz with this library to format the data, because I'm coming from python.

I tried the following format (2 col csv, no colnames) and got it to work in pm but there are no colors or links visible

Dennis_Ritchie,iPhone
Dennis_Ritchie,"Summit, New Jersey"
Dennis_Ritchie,File:Dennis Ritchie (right) Receiving Japan Prize.jpeg
Dennis_Ritchie,Firstpost
Dennis_Ritchie,"Category:People from Summit, New Jersey"
...... {continue 20k lines, not always dennis_ritchie}

Also I tried to update the indexer by koder-ua and got a format of

[
["freemusicarchive", null, "Failed to found link"],
["CodeAnalyzer", null, "Failed to found link"],
["wolfson", null, "Failed to found link"],
....... {210k lines]
]

but I didn't try running this to build position, links, labels, meta.

Do you have an example of a packages.csv laying around that you could add to the repo?

Cheers,
Sam

**Comment by anvaka** [comment]
Hi Sam, please use this guide to build your own visualization inside `pm`: 

https://github.com/anvaka/pm#your-own-graphs

Happy holidays 🎉 !
